### ISSUE TITLE
Associate your library with me and use FloatingActionButton to make a mistake

### ISSUE THREAD

**Issue by jiangzehui** [DreaminginCodeZH/MaterialRatingBar#16]
Associate your library with me and use FloatingActionButton to make a mistake

android.view.InflateException: Binary XML file line #61: Error inflating class android.support.design.widget.FloatingActionButton

**Comment by jiangzehui** [comment]
Caused by: java.lang.reflect.InvocationTargetException
                                                                                 at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                 at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:600)
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:769) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
                                                                                 at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143) 
                                                                                 at com.example.zhuineng01fortp.control.zn.WorkMsgActivity.onCreate(WorkMsgActivity.java:42) 
                                                                                 at android.app.Activity.performCreate(Activity.java:5372) 
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104) 
                                                                                 at cn.jiguang.a.a.d.a.a.d.callActivityOnCreate(Unknown Source) 
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257) 
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2348) 
                                                                                 at android.app.ActivityThread.access$700(ActivityThread.java:159) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                 at android.os.Looper.loop(Looper.java:137) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5415) 
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
                                                                                 at dalvik.system.NativeStart.main(Native Method) 
                                                                              Caused by: java.lang.NoSuchMethodError: android.support.v7.widget.AppCompatImageHelper.<init>
                                                                                 at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:133)
                                                                                 at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:110)
                                                                                 at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                 at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:600) 
                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:769) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
                                                                                 at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)

**Comment by zhanghai** [comment]
`Caused by: java.lang.NoSuchMethodError: android.support.v7.widget.AppCompatImageHelper.
at android.support.design.widget.FloatingActionButton.(FloatingActionButton.java:133)`

Either you have a ProGuard problem or you are using incorrect versions of support libraries: since the error is raised from support `FloatingActionButton`, it is unlikely to be a bug in this library.

IMHO it can be that you ended up mixing different versions of suppot library components. You can run `./gradlew dependencies` to see what the versions are, and you can check specifically for that of `appcompat-v7`.

The library currently depends on `com.android.support:appcompat-v7:25.0.0` which is out-dated now, but it shouldn't be of any problem because you should declare a newer version now and it will be promoted.
